openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: RESTful API for managing users and tasks with role-based access control.

servers:
  - url: http://localhost:5000

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, email, password]
              properties:
                username: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        '201':
          description: Registered successfully

  /api/auth/login:
    post:
      summary: Login and receive JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [emailOrUsername, password]
              properties:
                emailOrUsername: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Login successful

  /api/users/me:
    get:
      summary: Get logged-in user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile info

  /api/tasks:
    get:
      summary: Get tasks for user or team
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of tasks

    post:
      summary: Create a new task
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title: { type: string }
                description: { type: string }
                dueDate: { type: string, format: date }
                priority: { type: string }
      responses:
        '201':
          description: Task created

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT